	//IR操作码				跳转类型				操作数个数    常量传播类型          单词类型             死代码操作类型         代数化简类型            是否满足交换律
	{JMP,			Opti_Tbl::NonCondJmp	,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{JT,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{JNT,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{JE_1,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{JE_2,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{JE_4,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},

	{LABEL,			Opti_Tbl::Lbl			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{EQU,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			16,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{NEQU, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			19,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LS, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			18,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{MR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			21,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LE,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			20,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ME, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			22,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IN, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			63,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SUBI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			24,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ADDI,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			23,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{OR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			71,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{XOR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			93,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{MULI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			25,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{DIVI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			26,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{MOD,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			67,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SHR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			80,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{AND, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			41,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{SHL, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			78,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{NEG, 			Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::None,			24,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{NOT, 			Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::None,			69,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ASSIGN,		Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::ToAssign,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},

	{SUB_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{SUB_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_8,			Opti_Tbl::None},
	{SUB_8,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_8,			Opti_Tbl::None},
	{SUB_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::None},

	{ADD_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::Commutative},
	{ADD_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_8,			Opti_Tbl::Commutative},
	{ADD_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::Commutative},

	{OR_0,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::Commutative},
	{OR_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::Commutative},
	{OR_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::Commutative},
	{OR_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::Commutative},
	{DIV_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_8,			Opti_Tbl::None},
	{DIV_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{MUL_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_8,			Opti_Tbl::Commutative},
	{MUL_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::Commutative},
	{MOD_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{SHR_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{SHR_1U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::None},
	{SHR_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::None},
	{SHR_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::None},
	{SHR_2U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::None},
	{SHR_4U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{AND_0,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::Commutative},
	{AND_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::Commutative},
	{AND_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::Commutative},
	{AND_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::Commutative},
	{SHL_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},
	{SHL_1U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::None},
	{SHL_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_1,			Opti_Tbl::None},
	{SHL_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::None},
	{SHL_2U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_2,			Opti_Tbl::None},
	{SHL_4U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			ASSIGN_4,			Opti_Tbl::None},

	{ASM, 			Opti_Tbl::None			,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{CALL, 			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{GETPROCADDR,	Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{RETV, 			Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{PARA, 			Opti_Tbl::None			,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{SET_ADDITEM,	Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{CALLPTR,		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{GETADDR, 		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{TypeCast, 		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},

	{ChrToStr,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToInt,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToInt,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToReal,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SingleToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{RealToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToWord,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToByte,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ByteToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{ShortToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{SmallToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{IntToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{WordToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{LongToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None}
