	//IR操作码				跳转类型				操作数个数
	{OpType::JMP,			Opti_Tbl::NonCondJmp	,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::JT,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::JNT,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::JE_1,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::JE_2,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::JE_4,			Opti_Tbl::CondJmp		,Opti_Tbl::nExp1_2,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},

	{OpType::LABEL,			Opti_Tbl::Lbl			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::EQU,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			16,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::NEQU, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			19,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LS, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			18,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::MR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			21,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LE,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			20,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ME, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			22,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IN, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			63,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SUBI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			24,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ADDI,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			23,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{OpType::OR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			71,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::XOR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			93,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::MULI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			25,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{OpType::DIVI, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			26,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::MOD,			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			67,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SHR, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			80,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::AND, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			41,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::Commutative},
	{OpType::SHL, 			Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			78,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::NEG, 			Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::None,			24,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::NOT, 			Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::None,			69,					Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ASSIGN,		Opti_Tbl::None			,Opti_Tbl::Exp1_3,	Opti_Tbl::ToAssign,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},

	{OpType::SUB_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::SUB_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_8,			Opti_Tbl::None},
	{OpType::SUB_8,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_8,			Opti_Tbl::None},	
	{OpType::SUB_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::None},

	{OpType::ADD_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::Commutative},	
	{OpType::ADD_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_8,			Opti_Tbl::Commutative},
	{OpType::ADD_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::Commutative},	

	{OpType::OR_0,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::Commutative},
	{OpType::OR_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::Commutative},
	{OpType::OR_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::Commutative},
	{OpType::OR_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::Commutative},
	{OpType::DIV_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_8,			Opti_Tbl::None},
	{OpType::DIV_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::MUL_8F,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_8,			Opti_Tbl::Commutative},
	{OpType::MUL_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::Commutative},
	{OpType::MOD_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::SHR_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::SHR_1U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::None},
	{OpType::SHR_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::None},
	{OpType::SHR_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::None},
	{OpType::SHR_2U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::None},
	{OpType::SHR_4U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::AND_0,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::Commutative},
	{OpType::AND_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::Commutative},
	{OpType::AND_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::Commutative},
	{OpType::AND_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::Commutative},
	{OpType::SHL_4,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},
	{OpType::SHL_1U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::None},
	{OpType::SHL_1,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_1,			Opti_Tbl::None},
	{OpType::SHL_2,			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::None},
	{OpType::SHL_2U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_2,			Opti_Tbl::None},
	{OpType::SHL_4U,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			OpType::ASSIGN_4,			Opti_Tbl::None},

	{OpType::ASM, 			Opti_Tbl::None			,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::CALL, 			Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::GETPROCADDR,	Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::RETV, 			Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::PARA, 			Opti_Tbl::None			,Opti_Tbl::nExp1,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SET_ADDITEM,	Opti_Tbl::None			,Opti_Tbl::Exp1_2_3,Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::CALLPTR,		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::GETADDR, 		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::None,			Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::TypeCast, 		Opti_Tbl::None			,Opti_Tbl::nExp1_3,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},

	{OpType::ChrToStr,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::None,			Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToInt,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToInt,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToInt,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToInt,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToReal,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SingleToReal,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToReal,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::RealToSingle,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSingle,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToSmall,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToSmall,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToWord,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToWord,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToWord,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToLong,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToShort,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToShort,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToByte,		Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToByte,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToByte,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ByteToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::ShortToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::SmallToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::IntToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::WordToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None},
	{OpType::LongToLong8,	Opti_Tbl::None			,Opti_Tbl::None,	Opti_Tbl::ToLong8,		Opti_Tbl::None,		Opti_Tbl::DeadCode,		Opti_Tbl::None,			Opti_Tbl::None}